language: node_js

node_js:
  - '12'

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run build

before_deploy:
  - npm install netlify-cli -g
  - yarn build

deploy:
  provider: script
  edge: true
  script: netlify deploy --prod --dir ./build
  skip_cleanup: true
  on:
    branch: main
